import streamlit as st
import json
import re
from utils import load_data, get_week_info, GOAL_WEIGHT, START_WEIGHT

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

data = load_data()
wi   = get_week_info()
ws   = data.get("weights", {})
lw   = ws[sorted(ws.keys(), reverse=True)[0]] if ws else None

st.markdown('<p class="page-title">Nutrition planner</p>', unsafe_allow_html=True)
st.markdown('<p class="page-sub">Personalised meal plan generated by Claude AI based on your goals.</p>', unsafe_allow_html=True)

# ── Helpers ───────────────────────────────────────────────
def calc_tdee(weight, height, age, sex, activity_key):
    bmr = 10*weight + 6.25*height - 5*age + (5 if sex == "Male" else -161)
    mults = {
        "Sedentary (desk job)": 1.2,
        "Lightly active (1–2x/week)": 1.375,
        "Moderately active (3–5x/week)": 1.55,
        "Very active (6–7x/week)": 1.725,
    }
    return round(bmr * mults.get(activity_key, 1.55))

def generate_meal_plan(api_key, target_cal, protein_g, goal_type, allergies, diet, custom_exclude):
    exclude_list = allergies + ([custom_exclude] if custom_exclude else [])
    exclude_str  = ", ".join(exclude_list) if exclude_list else "none"
    diet_str     = diet if diet != "No restriction" else "no specific diet"

    prompt = f"""You are a professional nutritionist. Generate a detailed one-day meal plan.

User profile:
- Daily calorie target: {target_cal} kcal
- Protein target: {protein_g}g per day
- Goal: {goal_type}
- Diet type: {diet_str}
- Ingredients to EXCLUDE (allergies/dislikes): {exclude_str}

Generate exactly 3 meals: breakfast, lunch, and dinner.

Return ONLY a valid JSON object, no markdown, no extra text:
{{
  "meals": [
    {{
      "type": "Breakfast",
      "name": "Recipe name",
      "description": "Brief appetizing description (1-2 sentences)",
      "ingredients": [
        {{"name": "ingredient name", "amount": 100, "unit": "g"}}
      ],
      "instructions": ["Step 1...", "Step 2...", "Step 3..."],
      "prep_time": 10,
      "cook_time": 15,
      "calories": 450,
      "protein": 35,
      "carbs": 40,
      "fat": 12
    }},
    {{
      "type": "Lunch",
      "name": "Recipe name",
      "description": "Brief appetizing description",
      "ingredients": [{{"name": "ingredient", "amount": 150, "unit": "g"}}],
      "instructions": ["Step 1...", "Step 2..."],
      "prep_time": 10,
      "cook_time": 20,
      "calories": 600,
      "protein": 45,
      "carbs": 55,
      "fat": 18
    }},
    {{
      "type": "Dinner",
      "name": "Recipe name",
      "description": "Brief appetizing description",
      "ingredients": [{{"name": "ingredient", "amount": 200, "unit": "g"}}],
      "instructions": ["Step 1...", "Step 2..."],
      "prep_time": 15,
      "cook_time": 25,
      "calories": 500,
      "protein": 40,
      "carbs": 45,
      "fat": 15
    }}
  ],
  "daily_totals": {{
    "calories": 1550,
    "protein": 120,
    "carbs": 140,
    "fat": 45
  }},
  "tips": ["Tip 1 specific to this meal plan", "Tip 2", "Tip 3"]
}}

Rules:
- All amounts in grams or clear units
- Calories and macros must be realistic and accurate
- Recipes must be practical and easy to cook at home
- STRICTLY avoid all excluded ingredients in any form
- Total calories should be close to {target_cal} kcal"""

    try:
        r = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "Content-Type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 4000,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=60,
        )
        if r.status_code == 200:
            content = r.json()["content"][0]["text"]
            content = re.sub(r"```json|```", "", content).strip()
            start = content.find("{")
            end   = content.rfind("}") + 1
            return json.loads(content[start:end])
        else:
            return {"error": f"API error {r.status_code}: {r.text[:300]}"}
    except json.JSONDecodeError as e:
        return {"error": f"JSON parse error: {e}"}
    except Exception as e:
        return {"error": str(e)}

ALLERGY_MAP  = {
    "Gluten": "gluten", "Dairy": "dairy", "Eggs": "eggs",
    "Nuts": "tree nuts", "Peanuts": "peanuts", "Soy": "soy",
    "Seafood": "seafood", "Shellfish": "shellfish",
    "Pork": "pork", "Onions": "onions", "Salmon": "salmon",
}
DIET_OPTIONS = ["No restriction", "Vegetarian", "Vegan", "Gluten-free", "Ketogenic", "Paleo"]
MEAL_ICONS   = {"Breakfast": "🍳", "Lunch": "🍲", "Dinner": "🍽️"}

# ── Session state ─────────────────────────────────────────
for k, v in {
    "np_step": 1, "np_profile": {}, "np_allergies": [],
    "np_diet": "No restriction", "np_plan": None, "np_error": "",
}.items():
    if k not in st.session_state:
        st.session_state[k] = v

try:
    CLAUDE_KEY = st.secrets["ANTHROPIC_API_KEY"]
except Exception:
    CLAUDE_KEY = ""

# ── Step indicator ────────────────────────────────────────
step   = st.session_state.np_step
labels = ["Profile", "Preferences", "Your plan"]
scols  = st.columns(3)
for i, lbl in enumerate(labels):
    active = (i + 1 == step)
    done   = (i + 1 < step)
    color  = "#818cf8" if active else ("#34d399" if done else "#334155")
    scols[i].markdown(
        f'<div style="text-align:center;padding:8px 0;border-bottom:2px solid {color};">'
        f'<span style="font-size:12px;font-weight:600;color:{color};text-transform:uppercase;'
        f'letter-spacing:1px;font-family:\'JetBrains Mono\',monospace;">'
        f'{"✓ " if done else ""}{i+1}. {lbl}</span></div>',
        unsafe_allow_html=True,
    )
st.markdown("<br>", unsafe_allow_html=True)

# ════════════════════════════════════════════════════════
# STEP 1 — PROFILE
# ════════════════════════════════════════════════════════
if step == 1:
    st.markdown('<div class="sec-title">Your profile</div>', unsafe_allow_html=True)
    p = st.session_state.np_profile

    s1, s2 = st.columns(2)
    with s1:
        sex    = st.radio("Sex", ["Male", "Female"], horizontal=True,
                          index=0 if p.get("sex", "Male") == "Male" else 1)
        age    = st.number_input("Age", 16, 80, int(p.get("age", 25)))
        height = st.number_input("Height (cm)", 140, 220, int(p.get("height", 170)))
    with s2:
        weight      = st.number_input("Current weight (kg)", 40.0, 200.0,
                                      float(p.get("weight", float(lw if lw else START_WEIGHT))), step=0.5)
        goal_weight = st.number_input("Goal weight (kg)", 40.0, 200.0,
                                      float(p.get("goal_weight", GOAL_WEIGHT)), step=0.5)
        activity    = st.selectbox("Activity level", [
                          "Sedentary (desk job)", "Lightly active (1–2x/week)",
                          "Moderately active (3–5x/week)", "Very active (6–7x/week)"], index=2)

    goal_type    = st.selectbox("Goal", ["Lose weight (cut)", "Gain muscle (bulk)", "Maintain"], index=0)
    period_weeks = st.slider("Plan duration (weeks)", 4, 24, 8)

    tdee = calc_tdee(weight, height, age, sex, activity)
    if "cut" in goal_type:
        deficit    = 750 if (weight - goal_weight) / max(period_weeks / 4, 1) > 1 else 500
        target_cal = tdee - deficit
        goal_label = f"−{deficit} kcal deficit"
    elif "bulk" in goal_type:
        target_cal = tdee + 300
        goal_label = "+300 kcal surplus"
    else:
        target_cal = tdee
        goal_label = "maintenance"

    protein_g     = round(weight * (2.0 if "bulk" in goal_type else 1.8))
    weeks_to_goal = abs(round((weight - goal_weight) / (0.5 if "cut" in goal_type else 0.25))) if weight != goal_weight else 0

    st.markdown("<br>", unsafe_allow_html=True)
    pc1, pc2, pc3, pc4 = st.columns(4)
    with pc1:
        st.markdown(f'<div class="s-card"><div class="s-label">TDEE</div><div class="s-val" style="color:#818cf8;">{tdee}</div><div class="s-sub">kcal/day</div></div>', unsafe_allow_html=True)
    with pc2:
        st.markdown(f'<div class="s-card"><div class="s-label">Daily target</div><div class="s-val" style="color:#34d399;">{target_cal}</div><div class="s-sub">{goal_label}</div></div>', unsafe_allow_html=True)
    with pc3:
        st.markdown(f'<div class="s-card"><div class="s-label">Protein</div><div class="s-val" style="color:#fbbf24;">{protein_g}g</div><div class="s-sub">per day</div></div>', unsafe_allow_html=True)
    with pc4:
        st.markdown(f'<div class="s-card"><div class="s-label">Est. duration</div><div class="s-val" style="color:#f472b6;">{weeks_to_goal}w</div><div class="s-sub">to {goal_weight} kg</div></div>', unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("Continue →", use_container_width=True):
        st.session_state.np_profile = dict(
            sex=sex, age=age, height=height, weight=weight,
            goal_weight=goal_weight, activity=activity, goal_type=goal_type,
            period_weeks=period_weeks, tdee=tdee,
            target_cal=target_cal, protein_g=protein_g,
        )
        st.session_state.np_step = 2
        st.rerun()

# ════════════════════════════════════════════════════════
# STEP 2 — PREFERENCES
# ════════════════════════════════════════════════════════
elif step == 2:
    st.markdown('<div class="sec-title">Dietary preferences</div>', unsafe_allow_html=True)

    diet = st.selectbox("Diet type", DIET_OPTIONS,
                        index=DIET_OPTIONS.index(st.session_state.get("np_diet", "No restriction")))

    st.markdown("<br>**Allergies & exclusions:**")
    acols = st.columns(4)
    prev  = st.session_state.np_allergies
    selected_allergies = []
    for i, (label, val) in enumerate(ALLERGY_MAP.items()):
        with acols[i % 4]:
            if st.checkbox(label, value=(label.lower() in prev or val in prev), key=f"al_{label}"):
                selected_allergies.append(label.lower())

    st.markdown("<br>", unsafe_allow_html=True)
    custom_ex = st.text_input(
        "Other ingredients to exclude (comma-separated)",
        placeholder="e.g. mushrooms, cilantro",
        key="np_custom_ex",
    )

    if not CLAUDE_KEY:
        st.warning("⚠️ No Anthropic API key. Add `ANTHROPIC_API_KEY` to `.streamlit/secrets.toml`.")

    st.markdown("<br>", unsafe_allow_html=True)
    b1, b2 = st.columns(2)
    with b1:
        if st.button("← Back", use_container_width=True):
            st.session_state.np_step = 1
            st.rerun()
    with b2:
        if st.button("✨ Generate meal plan", use_container_width=True,
                     disabled=not CLAUDE_KEY, type="primary"):
            st.session_state.np_allergies = selected_allergies
            st.session_state.np_diet      = diet
            st.session_state.np_plan      = None
            st.session_state.np_error     = ""
            profile = st.session_state.np_profile
            with st.spinner("Claude is creating your personalised meal plan…"):
                result = generate_meal_plan(
                    CLAUDE_KEY,
                    profile["target_cal"],
                    profile["protein_g"],
                    profile["goal_type"],
                    selected_allergies,
                    diet,
                    custom_ex.strip(),
                )
            if "error" in result:
                st.session_state.np_error = result["error"]
            else:
                st.session_state.np_plan = result
            st.session_state.np_step = 3
            st.rerun()

# ════════════════════════════════════════════════════════
# STEP 3 — RESULTS
# ════════════════════════════════════════════════════════
elif step == 3:
    profile = st.session_state.np_profile
    plan    = st.session_state.np_plan
    error   = st.session_state.np_error

    rb1, rb2 = st.columns([1, 3])
    with rb1:
        if st.button("← Edit profile"):
            st.session_state.np_step = 1
            st.rerun()
    with rb2:
        if st.button("🔄 Regenerate plan", use_container_width=True):
            st.session_state.np_step = 2
            st.rerun()

    st.markdown("<br>", unsafe_allow_html=True)

    if error:
        st.markdown(f"""
        <div style="background:rgba(239,68,68,0.08);border:1px solid rgba(239,68,68,0.2);
        border-radius:14px;padding:20px 24px;">
          <div style="font-size:15px;font-weight:600;color:#fca5a5;">⚠️ {error}</div>
          <div style="font-size:13px;color:#7f1d1d;margin-top:6px;">Click ← Edit profile or 🔄 Regenerate to try again.</div>
        </div>""", unsafe_allow_html=True)

    elif plan:
        meals  = plan.get("meals", [])
        totals = plan.get("daily_totals", {})
        tips   = plan.get("tips", [])

        # ── Summary cards ─────────────────────────────────
        st.markdown('<div class="sec-title">Daily summary</div>', unsafe_allow_html=True)
        nc1, nc2, nc3, nc4, nc5 = st.columns(5)
        target_cal = profile.get("target_cal", 0)
        plan_cal   = totals.get("calories", 0)
        diff       = plan_cal - target_cal
        diff_color = "#34d399" if abs(diff) <= 100 else ("#fbbf24" if abs(diff) <= 200 else "#ef4444")

        for col, (lbl, val, color, sub) in zip([nc1, nc2, nc3, nc4, nc5], [
            ("Target",  target_cal,                 "#818cf8", "kcal/day"),
            ("Planned", plan_cal,                   diff_color, f"{diff:+d} kcal"),
            ("Protein", totals.get("protein", 0),   "#fbbf24", f"target {profile.get('protein_g',0)}g"),
            ("Carbs",   totals.get("carbs", 0),     "#60a5fa", "grams"),
            ("Fat",     totals.get("fat", 0),       "#f472b6", "grams"),
        ]):
            col.markdown(
                f'<div class="s-card"><div class="s-label">{lbl}</div>'
                f'<div class="s-val" style="color:{color};font-size:22px;">{val}</div>'
                f'<div class="s-sub">{sub}</div></div>',
                unsafe_allow_html=True,
            )

        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown('<div class="sec-title">Your meals</div>', unsafe_allow_html=True)

        # ── Meal cards ────────────────────────────────────
        for meal in meals:
            meal_type = meal.get("type", "Meal")
            icon      = MEAL_ICONS.get(meal_type, "🍽️")
            name      = meal.get("name", "")
            desc      = meal.get("description", "")
            cal       = meal.get("calories", "—")
            prot      = meal.get("protein", "—")
            carbs_val = meal.get("carbs", "—")
            fat_val   = meal.get("fat", "—")
            prep      = meal.get("prep_time", 0)
            cook      = meal.get("cook_time", 0)
            ingrs     = meal.get("ingredients", [])
            steps     = meal.get("instructions", [])
            total_time = prep + cook if isinstance(prep, int) and isinstance(cook, int) else "—"

            st.markdown(f"""
            <div style="background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.07);
            border-radius:16px;padding:20px 24px;margin-bottom:16px;">
              <div style="font-size:11px;font-weight:600;color:#64748b;text-transform:uppercase;
              letter-spacing:1.5px;font-family:'JetBrains Mono',monospace;margin-bottom:8px;">{icon} {meal_type}</div>
              <div style="font-size:19px;font-weight:700;color:#f1f5f9;margin-bottom:6px;">{name}</div>
              <div style="font-size:13px;color:#64748b;margin-bottom:14px;">{desc}</div>
              <div style="display:flex;gap:8px;flex-wrap:wrap;">
                <span style="font-size:12px;background:rgba(129,140,248,0.1);color:#818cf8;padding:3px 12px;border-radius:6px;font-family:'JetBrains Mono',monospace;">🔥 {cal} kcal</span>
                <span style="font-size:12px;background:rgba(251,191,36,0.1);color:#fbbf24;padding:3px 12px;border-radius:6px;font-family:'JetBrains Mono',monospace;">💪 {prot}g protein</span>
                <span style="font-size:12px;background:rgba(96,165,250,0.1);color:#60a5fa;padding:3px 12px;border-radius:6px;font-family:'JetBrains Mono',monospace;">🌾 {carbs_val}g carbs</span>
                <span style="font-size:12px;background:rgba(244,114,182,0.1);color:#f472b6;padding:3px 12px;border-radius:6px;font-family:'JetBrains Mono',monospace;">🥑 {fat_val}g fat</span>
                <span style="font-size:12px;background:rgba(255,255,255,0.05);color:#64748b;padding:3px 12px;border-radius:6px;font-family:'JetBrains Mono',monospace;">⏱ {total_time} min</span>
              </div>
            </div>""", unsafe_allow_html=True)

            with st.expander(f"🛒 Ingredients ({len(ingrs)})"):
                ing_cols = st.columns(2)
                for j, ing in enumerate(ingrs):
                    amt   = ing.get("amount", "")
                    unit  = ing.get("unit", "")
                    iname = ing.get("name", "")
                    with ing_cols[j % 2]:
                        st.markdown(
                            f'<div style="font-size:13px;color:#94a3b8;padding:4px 0;'
                            f'border-bottom:1px solid rgba(255,255,255,0.04);">'
                            f'<span style="color:#e2e8f0;font-weight:500;">{amt}{unit}</span> {iname}</div>',
                            unsafe_allow_html=True,
                        )

            with st.expander(f"👨‍🍳 Instructions ({len(steps)} steps)"):
                for j, step_txt in enumerate(steps):
                    st.markdown(
                        f'<div style="display:flex;gap:12px;padding:8px 0;'
                        f'border-bottom:1px solid rgba(255,255,255,0.04);">'
                        f'<span style="font-size:12px;font-weight:700;color:#818cf8;min-width:24px;'
                        f'font-family:\'JetBrains Mono\',monospace;">{j+1}.</span>'
                        f'<span style="font-size:13px;color:#94a3b8;line-height:1.6;">{step_txt}</span></div>',
                        unsafe_allow_html=True,
                    )

        # ── Tips ──────────────────────────────────────────
        if tips:
            st.markdown("<br>", unsafe_allow_html=True)
            tips_html = "".join(f'<div style="font-size:13px;color:#94a3b8;padding:4px 0;line-height:1.6;">→ {t}</div>' for t in tips)
            st.markdown(f"""
            <div style="background:rgba(16,185,129,0.05);border:1px solid rgba(16,185,129,0.15);
            border-radius:14px;padding:18px 22px;">
              <div style="font-size:13px;font-weight:600;color:#6ee7b7;margin-bottom:10px;">💡 Personalised tips</div>
              {tips_html}
            </div>""", unsafe_allow_html=True)

        st.markdown("""
        <div style="background:rgba(239,68,68,0.05);border:1px solid rgba(239,68,68,0.12);
        border-radius:14px;padding:16px 20px;margin-top:12px;">
          <div style="font-size:13px;font-weight:600;color:#fca5a5;margin-bottom:6px;">❌ Always avoid</div>
          <div style="font-size:13px;color:#94a3b8;line-height:1.8;">
            Sugary drinks · Ultra-processed snacks · Late-night eating after 11 PM · Fried food · Alcohol
          </div>
        </div>""", unsafe_allow_html=True)

    else:
        st.info("Something went wrong. Click ← Edit profile to try again.")
